[tasks.bc]
description = "Start Blockchain Server"
script = ['''
#!/usr/bin/env bash
cd blockchain && cargo run src/main.rs
''']

[tasks.ts]
description = "Test Blockchain Function"
script = ['''
#!/usr/bin/env bash
(cd blockchain && cargo test)
(cd integration && cargo test)
''']

[tasks.it]
description = "Start Integrated Blockchain"
script = ['''
#!/usr/bin/env bash
cd integration && cargo run
''']

[tasks.get]
description = "Http Get Request"
script = ['''
#!/usr/bin/env bash
curl http://localhost:3000/whole_blockchain
''']

[tasks.post]
description = "Http Post Request"
script = ['''
#!/usr/bin/env bash
curl -d '{"hobby":"rock", "life":"rock"}' -H "Content-Type: application/json" -X POST http://localhost:${@}/check_all
''']
