[tasks.bc]
description = "Start Blockchain Server"
script = ['''
#!/usr/bin/env bash
cd blockchain && cargo run src/main.rs
''']

[tasks.ts]
description = "Test Blockchain Function"
script = ['''
#!/usr/bin/env bash
cd blockchain && cargo test
''']
