[tasks.it]
description = "Start Blockchain Server"
script = ['''
#!/usr/bin/env bash
(cd blockchain && cargo test)
(cd integration && cargo test)
(cd lamport-sig && cargo test)
(cd merkle-tree && cargo test)
(cd p2p/client && cargo test)
(cd p2p/server && cargo test)
(cd transaction && cargo test)
(cd wallet && cargo test)
(cd utxo && cargo test)
''']
