[tasks.server]
description = "Start Server"
script = ['''
#!/usr/bin/env bash
cd server && cargo run
''']

[tasks.client]
description = "Start Client"
script = ['''
#!/usr/bin/env bash
cd client && cargo run
''']
