[tasks.run]
description = "Start Blockchain Server"
script = ['''
#!/usr/bin/env bash
cargo run
''']

[tasks.get]
description = "Http Post Request"
script = ['''
#!/usr/bin/env bash
curl  http://localhost:3000/
''']

[tasks.tx]
description = "Send Transaction"
script = ['''
#!/usr/bin/env bash
curl -d '{"amount": 100, "sender":"alice", "recipient":"bob"}' -H "Content-Type: application/json" -X POST http://localhost:3000/send_transaction
''']

[tasks.new]
description = "Create New Block"
script = ['''
#!/usr/bin/env bash
curl  http://localhost:3000/create_new_block
''']
