[tasks.get]
description = "Http Post Request"
script = ['''
#!/usr/bin/env bash
curl  http://localhost:${@}/
''']

[tasks.add]
description = "Http Post Request"
script = ['''
#!/usr/bin/env bash
curl -d '{"endpoint":"127.0.0.1:5000"}' -H "Content-Type: application/json" -X POST http://localhost:${@}/add
''']
