name: Rust Cargo Test

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: blockchain tests
      run: cd blockchain && cargo test --verbose

    - name: install dependencies
      run: cargo install --force cargo-make

    - name: integration test
      run: makers ts
