name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
    - run: cd blockchain && cargo test --verbose
    - run: cd integration && cargo test --verbose
